name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate Snake Animation

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Anish-2005
          output: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "Updated Snake Animation"
          add: "dist/github-contribution-grid-snake.svg"
          author_name: "GitHub Action"
          author_email: "actions@github.com"
